version: "3.4"
services:
  api:
    image: "snax4a/offer-exchange-api:${API_TAG}"
    environment:
      - "MultitenancySettings__ConnectionString=server=db;uid=root;pwd=${DB_PASSWORD};dat\
        abase=rootTenantDb;Allow User Variables=True"
      - "MultitenancySettings__DBProvider=mysql"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=${DB_PASSWORD}"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_URLS=https://+:5052;http://+:5062"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5052:5052"
      - "5062:5062"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    container_name: api

  db:
    image: "mysql:8"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    container_name: mysql
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${DB_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
