volumes:
  offer_exchange_dev_data:
  offer_exchange_dev_seq_data:

services:
  api:
    image: "snax4a/offer-exchange-api:1.0.2"
    container_name: api
    environment:
      - "DatabaseSettings__ConnectionString=Host=db;Database=offer_exchange;\
        Username=oe;Password=DEV-DB-PASSWORD;Include Error Detail=true"
      - "DatabaseSettings__DBProvider=postgresql"
      - "HangfireSettings__Storage__ConnectionString=Host=db;Database=offer_exchange;\
        Username=oe;Password=DEV-DB-PASSWORD;Include Error Detail=true"
      - "HangfireSettings__Storage__StorageProvider=PostgreSQL"
      - "HangfireSettings__Credentials__User=Admin"
      - "HangfireSettings__Credentials__Password=DEV_HANGFIRE_PASSWORD"
      - "HangfireSettings__Dashboard__StatsPollingInterval=10000"
      - "SwaggerSettings__Enable=false"
      - "MiddlewareSettings__EnableHttpsLogging=true"
      - "CorsSettings__React=http://localhost:3000"
      - "SecuritySettings__JwtSettings__key=DEV-JVT-KEY-hZsXLAvNnEluHBKYj61XmkORlKV3"
      - "MailSettings__DisplayName=Offer Exchange"
      - "MailSettings__From=noreply@offerexchange.net"
      - "MailSettings__Host=smtp.mailtrap.io"
      - "MailSettings__Password=4690dab20a8c60"
      - "MailSettings__Port=587"
      - "MailSettings__UserName=cad0b7a4c580d7"
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain1.pem
      # - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey1.pem
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devCertPassw0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/offer_exchange_dev.pfx
    volumes:
      # - /home/certy/api.beta.offerexchange.net:/https:ro
      - ./https:/https:ro
      - ./logs:/app/Logs:rw
    ports:
      - "5050:5050"
      - "5060:5060"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=offer_exchange
      - POSTGRES_USER=oe
      - POSTGRES_PASSWORD=DEV-DB-PASSWORD
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - offer_exchange_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oe -d offer_exchange"]
      interval: 20s
      timeout: 5s
      retries: 5

  seq:
    image: "datalust/seq:latest"
    container_name: seq
    restart: unless-stopped
    volumes:
      - offer_exchange_dev_seq_data:/data
    depends_on:
      - api
    ports:
      - "5070:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH=
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
