volumes:
  offer_exchange_db_data:
  offer_exchange_seq_data:

services:
  api:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${CERT_FILENAME}
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/${CERT_KEY_FILENAME}

  db:
    volumes:
      - offer_exchange_db_data:/var/lib/postgresql/data

  seq:
    image: "datalust/seq:2022.1"
    container_name: seq
    restart: unless-stopped
    volumes:
      - offer_exchange_seq_data:/data
    depends_on:
      - api
    ports:
      - "5070:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMIN_PASSWORD_HASH}
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  pgbackups:
    container_name: postgres_backups
    image: prodrigestivill/postgres-backup-local:14-alpine
    restart: unless-stopped
    volumes:
      - ./backups:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=--compress=6 --format=directory --jobs=4
      - SCHEDULE=@daily
      - TZ=Europe/Warsaw
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=5088
