volumes:
  offer_exchange_db_data:
  offer_exchange_seq_data:

services:
  api:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${CERT_FILENAME}
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/${CERT_KEY_FILENAME}

  db:
    volumes:
      - offer_exchange_db_data:/var/lib/postgresql/data

  seq:
    image: "datalust/seq:2022.1"
    container_name: seq
    restart: unless-stopped
    volumes:
      - offer_exchange_seq_data:/data
    depends_on:
      - api
    ports:
      - "5070:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMIN_PASSWORD_HASH}
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
